function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){if($(window).width()>=960){var t228_navLinks=$("#rec"+recid+" .t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){setTimeout(function(){t228_catchScroll(t228_navLinks)},500)}}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=new Array(),t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=$(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref($(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=$(this)});t228_updateSectionsOffsets(t228_sections);t228_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t228_updateSectionsOffsets(t228_sections)},200));$('.t228').bind('displayChanged',function(){t228_updateSectionsOffsets(t228_sections)});setInterval(function(){t228_updateSectionsOffsets(t228_sections)},5000);t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var t228_clickedSection=t228_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t228_clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');$(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_updateSectionsOffsets(sections){$(sections).each(function(){var t228_curSection=$(this);t228_curSection.attr("data-offset-top",t228_curSection.offset().top)})}
function t228_getSectionByHref(curlink){var t228_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t228_curLinkValue[0]=='/'){t228_curLinkValue=t228_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t228_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t228_curLinkValue.substring(1)+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=$(window).scrollTop(),t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!=0&&t228_clickedSectionId==null&&t228_sections[t228_sections.length-1].attr("data-offset-top")>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
$(t228_sections).each(function(e){var t228_curSection=$(this),t228_sectionTop=t228_curSection.attr("data-offset-top"),t228_id=t228_curSection.attr('id'),t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=$(document).height()-$(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setPath(){}
function t228_setWidth(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth(!0);if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}}
function t228_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");var topoffset=el.data('top-offset');if(topoffset&&parseInt(topoffset)>0){el.animate({"opacity":"1","top":topoffset+"px"},200,function(){})}else{el.animate({"opacity":"1","top":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}}})}}
function t228_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t228"),burger=el.find(".t228__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t228_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t383_highlight(link){if(link&&link!=''){$("a[href='"+link+"']").addClass("t-active")}}
function t389_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t397_init(recid){var el=$('#rec'+recid);el.find('.t397__tab').click(function(){el.find('.t397__tab').removeClass('t397__tab_active');$(this).addClass('t397__tab_active');t397_alltabs_updateContent(recid);t397_updateSelect(recid);$('.t230, .t670, .t347, .t346, .t519, .t774, .t764, .t744, .t349, .t650, .t604, .t117, .t517, .t609, .t351, .t353, .t341, .t404, .t385, .t386, .t412, .t268, .t425, .t409, .t384, .t279, .t428, .t418, .t433, .t121, .t478, .t498, .t552, .t544, .t554, .t545, .t486, .t570, .t422, .t601, .t228, .t229, .t456, .t592, .t520, .t599, .t422, .t504, .t688, .t675, .t132, .t616, .t686, .t778, .t615, .t433, .t598, .t762, .t538, .t226, .t698, .t760, .t511, .t799, .t780, .t827, .t740, .t480, .t827, .t829, .t605, .t726, .t728, .t822, .t798, .t801, .t694, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t396, .t518, .t738, .t532').trigger('displayChanged');setTimeout(function(){$('.t351, .t353, .t341, .t404, .t385, .t386, .t412, .t268, .t425, .t409, .t384, .t279, .t428, .t433, .t545, .t422, .t410, .t829, .t396, .t738').trigger('displayChanged')},50);if(window.lazy=='y'){t_lazyload_update()}});t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);$('.t397').bind('displayChanged',function(){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid)});var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t397__select, .t397__firefoxfix");bgcolor_target.css("background-color",bgcolor)}
function t397_alltabs_updateContent(recid){var el=$('#rec'+recid);el.find(".t397__tab").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.attr('data-connect-with-tab','yes');rec_el.attr('data-animationappear','off');rec_el.addClass('t379__off')})});el.find(".t397__tab_active").each(function(i){if($(this).is(":visible")||el.find(".t397__select").is(":visible")){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.removeClass('t379__off');rec_el.css('opacity','')})}})}
function t397_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t397__select").change(function(){var select_val=el.find(".t397__select").val();var tab_index=el.find(".t397__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t397_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t397__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t397__select");el_select.val(current_tab)}
function t537_setHeight(recid){var t537__el=$("#rec"+recid),t537__image=t537__el.find(".t537__bgimg:first"),t537__width=t537__image.attr("data-image-width"),t537__height=t537__image.attr("data-image-height"),t537__ratio=t537__height/t537__width,t537__padding=t537__ratio*100;$("#rec"+recid+" .t537__bgimg").css("padding-bottom",t537__padding+"%")}
function t582_init(recid){$(document).ready(function(){var t582__showMenu;$(window).bind('scroll',t_throttle(function(){clearTimeout(t582__showMenu);t582__showMenu=setTimeout(function(){t582_appearMenu(recid)},50)},200));$('.t582').removeClass('t582__beforeready');t582_appearMenu(recid)})}
function t582_appearMenu(recid){$(".t582").each(function(){var el=$(this),appearoffset=el.attr("data-appearoffset"),window_width=$(window).width(),window_scrollTop=$(window).scrollTop(),window_height=$(window).height();if(window_width<=980&&appearoffset!=""){appearoffset="150"}
if(appearoffset==""){appearoffset="0"}
if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window_height*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if(window_scrollTop>=appearoffset&&window_scrollTop+window_height+70<=$(document).height()){if(el.css('visibility')=='hidden'){el.finish();el.css("bottom","-100px");el.css("visibility","visible");el.animate({"opacity":"1","bottom":"0"},400,function(){})}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}})}
function t585_init(recid){var el=$('#rec'+recid),toggler=el.find(".t585__header");toggler.click(function(){$(this).toggleClass("t585__opened");$(this).next().slideToggle();if(window.lazy=='y'){t_lazyload_update()}})}
function t654_showPanel(recid){var t654_el=$('#rec'+recid),t654_block=t654_el.find('.t654'),t654_closeBtn=t654_el.find('.t654__icon-close'),t654_storageItem=t654_block.attr('data-storage-item'),t654_lastOpen=localStorage.getItem(t654_storageItem),t654_delta=t654_block.attr('data-storage-delta')*86400,t654_today=Math.floor(Date.now()/1000),t654_curDelta=t654_today-t654_lastOpen;if(t654_lastOpen==null||t654_curDelta>=t654_delta){t654_block.removeClass('t654_closed')}
t654_closeBtn.click(function(e){t654_block.addClass('t654_closed');if(t654_delta){localStorage.setItem(t654_storageItem,Math.floor(Date.now()/1000))}
e.preventDefault()})}
function t654_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t654").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t654").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t654_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t654").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();if(el.hasClass('t654_top')){el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}else{el.css("bottom","-50px");el.css("visibility","visible");el.animate({"opacity":"1","bottom":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden")}}})}}
function t654_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t654").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t696_onSuccess(t696_form){var t696_inputsWrapper=t696_form.find('.t-form__inputsbox');var t696_inputsHeight=t696_inputsWrapper.height();var t696_inputsOffset=t696_inputsWrapper.offset().top;var t696_inputsBottom=t696_inputsHeight+t696_inputsOffset;var t696_targetOffset=t696_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t696_target=t696_targetOffset-200}else{var t696_target=t696_targetOffset-100}
if(t696_targetOffset>$(window).scrollTop()||($(document).height()-t696_inputsBottom)<($(window).height()-100)){t696_inputsWrapper.addClass('t696__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t696_target},400);setTimeout(function(){t696_inputsWrapper.addClass('t696__inputsbox_hidden')},400)}
var successurl=t696_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy=='y'){t_lazyload_update()}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').click(function(e){if(e.target==this){t702_closePopup()}});el.find('.t-popup__close').click(function(e){t702_closePopup()});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup()}})}
function t702_closePopup(){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t708_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t708__popup'),analitics=el.attr('data-track-popup'),hook="TildaSendMessageWidget"+recid,obj=$('#rec'+recid+' .t708__btn');obj.click(function(e){if(obj.hasClass("t708__btn_active")){t708_closePopup();return}
obj.addClass("t708__btn_active");$('#rec'+recid+' .t708').addClass("t708_active");t708_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}
function t708_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');console.log("class added");body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t708_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t708_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t708__popup');$('.t708__btn_wrapper').removeClass('t708__btn_animate');$('.t708__btn-text').css('display','none');if($(window).width()<960){$('body').addClass('t708__body_popupshowed')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&$(window).width()<960){console.log("lock scroll");setTimeout(function(){t708_lockScroll()},500)}
popup.css('display','block');el.find('.t-range').trigger('popupOpened');setTimeout(function(){popup.addClass('t708__popup_show')},50);el.find(".t708__mobile-icon-close").click(function(e){t708_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t708_closePopup()}})}
function t708_closePopup(){if($(window).width()<960){$('body').removeClass('t708__body_popupshowed')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t708_unlockScroll()}
$('.t708').removeClass("t708_active");$('.t708__btn').removeClass('t708__btn_active');$('.t708__popup').removeClass('t708__popup_show');setTimeout(function(){$('.t708__popup').not('.t708__popup_show').css('display','none')},300)}
function t708_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t708_onSuccess(t708_form){var t708_inputsWrapper=t708_form.find('.t-form__inputsbox');var t708_inputsHeight=t708_inputsWrapper.height();var t708_inputsOffset=t708_inputsWrapper.offset().top;var t708_inputsBottom=t708_inputsHeight+t708_inputsOffset;var t708_targetOffset=t708_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t708_target=t708_targetOffset-200}else{var t708_target=t708_targetOffset-100}
if(t708_targetOffset>$(window).scrollTop()||($(document).height()-t708_inputsBottom)<($(window).height()-100)){t708_inputsWrapper.addClass('t708__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t708_target},400);setTimeout(function(){t708_inputsWrapper.addClass('t708__inputsbox_hidden')},400)}
var successurl=t708_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_onSuccess(t712_form){var t712_inputsWrapper=t712_form.find('.t-form__inputsbox');var t712_inputsHeight=t712_inputsWrapper.height();var t712_inputsOffset=t712_inputsWrapper.offset().top;var t712_inputsBottom=t712_inputsHeight+t712_inputsOffset;var t712_targetOffset=t712_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t712_target=t712_targetOffset-200}else{var t712_target=t712_targetOffset-100}
if(t712_targetOffset>$(window).scrollTop()||($(document).height()-t712_inputsBottom)<($(window).height()-100)){t712_inputsWrapper.addClass('t712__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t712_target},400);setTimeout(function(){t712_inputsWrapper.addClass('t712__inputsbox_hidden')},400)}
var successurl=t712_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t814_init(recid){t814_setHeight(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t814_setHeight(recid)},200));$('.t814').bind('displayChanged',function(){t814_setHeight(recid)})}
function t814_setHeight(rec){el=$('#rec'+rec)
var imgWrapperHeight=el.find(".t814__blockimg").height();var blockTextWrapper=el.find(".t814__blocktext-wrapper");var textWrapper=el.find(".t814__blocktext");if($(window).width()>960){textWrapper.css('height',imgWrapperHeight);blockTextWrapper.css('height',textWrapper.outerHeight(!0))}else{blockTextWrapper.css('height','auto')}}
function t833_init(recid){t833_startAnimation(recid)}
function t833_showOnCertainWidth(el,wrapper){el.attr('class').split(' ').forEach(function(item){if(item.indexOf('t-screen')!==-1){wrapper.addClass(item)}})}
function t833_startAnimation(recid){var el=$('#rec'+recid);var wrapper=el.find('.t833__sliderwrapper');var wr=el.find('.t833');var recs=wr.attr('data-coverslider-rec-ids');t833_showOnCertainWidth(el,wrapper);if($('#allrecords').attr('data-tilda-mode')==='edit'){t833_addAnimation(el.find('.t833__demo'),wrapper);return}
if(typeof recs!=='undefined'){recs=recs.split(',');recs.forEach(function(rec,index,array){var curRec=$('#rec'+rec);var curWrapper=wrapper.clone().css('position','absolute');t833_addAnimation(curRec,curWrapper)})}else{var nextBlock=el.next(':has(.t-cover)');var prevBlock=el.prev(':has(.t-cover)');var curWrapper=wrapper.clone().css('position','absolute');if(nextBlock.length!==0){t833_addAnimation(nextBlock,curWrapper)}else if(prevBlock.length!==0){t833_addAnimation(prevBlock,curWrapper)}}}
function t833_addAnimation(curRec,wrapper){curRec.attr('data-animationappear','off').removeClass('r_hidden');var curRecType=curRec.attr('data-record-type');var curRecId=curRec.attr('id');if(curRecType==='396'){curRec.find('.t396__filter').after(wrapper);wrapper.css('z-index','0')}
var coverWrapper=curRec.find('.t-cover');if(coverWrapper.length>0){coverWrapper.find('.t-cover__filter').after(wrapper);wrapper.css('z-index','0')}
if(curRec.length!=0){$(window).load(function(){t833_changeSlide(curRec)})}
var slider=curRec.find('.t833__slider');var slide=curRec.find('.t833__slide');var numberOfSlides=slide.length;if(numberOfSlides===3||numberOfSlides===2){slide.clone().appendTo(slider)}}
function t833_changeSlide(curRec){var slide=curRec.find('.t833__slide');var firstSlide=curRec.find('.t833__slide:first-child');var numberOfSlides=slide.length;var i=1;firstSlide.addClass('t833__slide_fx1');window.setInterval(t833_kenBurns,5000);function t833_kenBurns(){if(i==numberOfSlides){i=0}
$(slide[i]).addClass('t833__slide_fx');if(i===0){$(slide[numberOfSlides-2]).removeClass('t833__slide_fx t833__slide_fx1')}
if(i===1){$(slide[numberOfSlides-1]).removeClass('t833__slide_fx t833__slide_fx1');slide.removeClass('t833__slide_opacity')}
if(i>1){$(slide[i-2]).removeClass('t833__slide_fx t833__slide_fx1')}
i++}}